name: PureScript Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install PureScript and Spago
      run: npm install -g purescript spago@next
        
    - name: Install project dependencies
      run: spago install
      
    - name: Build project
      run: spago build
      
    - name: Run tests
      run: spago test
